FROM node:latest AS builder
WORKDIR /usr/src/app
COPY package*.json  ./
RUN npm i -g @angular/cli
ENV PATH /usr/src/app/node_modules/.bin:$PATH
RUN npm i --unsafe-perm

COPY . .
ARG node_env=production
ENV NODE_ENV $node_env

ARG project
RUN ng build $project --prod

WORKDIR /usr/src/app/dist/apps/$project
CMD ["node", "main.js"]
EXPOSE 3333


